Ec graph issue 31
dansjack/covid-score-app pull request #40
Opened 2020-11-03 07:56 UTC by chonger878

## Summary
Closes #31

A graph of the relationship between group size and risk is displayed.  Data points are displayed on the graph.
If there are many changes, make a list of them
* Added a title to the graph

## Checklist
- [ ] New tests added to account for changes in this MR
- [ ] All tests passing locally
- [ ] All tests passing on CircleCI
- [x ] Assigned at least 2 reviewers

2020-11-17 09:28 UTC, unicornsleuth commented on build.gradle
> +
We want 4.0.1 or 4.0.2

2020-11-17 09:29 UTC, unicornsleuth commented on gradle/wrapper/gradle-wrapper.properties
> +distributionUrl=https\://services.gradle.org/distributions/gradle-6.5-bin.zip
revert this file change

2020-11-17 09:29 UTC, unicornsleuth requested changes
Looks great! Just change some of the build files and you're good to go!

2020-11-17 20:05 UTC, chonger878 commented on build.gradle
> +
Done and done.

2020-11-17 20:05 UTC, chonger878 commented on gradle/wrapper/gradle-wrapper.properties
> +distributionUrl=https\://services.gradle.org/distributions/gradle-6.5-bin.zip
done and Done.

2020-11-18 01:30 UTC, dansjack approved these changes
Looks great! It still looks good when rotating the device too

2020-11-18 02:08 UTC, unicornsleuth approved these changes
Works as expected, and thanks for making the changes I requested!

2020-11-18 02:08 UTC, merged